CREATE TABLE USERS (
	ID INT NOT NULL PRIMARY KEY,
	EMAIL VARCHAR(256) NOT NULL,
	NAME VARCHAR(256) NOT NULL,
	BIRTHDAY DATE NOT NULL
);

CREATE TABLE AUDITORIUM (
	ID INT NOT NULL,
	NAME VARCHAR(256) NOT NULL,
	NUMBER INT NOT NULL,
	CONSTRAINT AUDITORIUM_PK PRIMARY KEY(ID)
);

CREATE TABLE SEAT_TYPE (
	ID INT NOT NULL,
	TYPE VARCHAR(256) NOT NULL,
	CONSTRAINT SEAT_TYPE_PK PRIMARY KEY(ID)
);

CREATE TABLE SEAT (
	ID INT NOT NULL,
	NUMBER INT NOT NULL,
	TYPE_ID INT NOT NULL,
	CONSTRAINT SEAT_PK PRIMARY KEY(ID),
	CONSTRAINT SEAT_FK1 FOREIGN KEY(TYPE_ID) REFERENCES SEAT_TYPE(ID)
);

CREATE TABLE AUDITORIUM_SEAT (
	AUDITORIUM_ID INT NOT NULL,
	SEAT_ID INT NOT NULL,
	CONSTRAINT AUDITORIUM_SEAT_PK PRIMARY KEY(AUDITORIUM_ID, SEAT_ID),
	CONSTRAINT AUDITORIUM_SEAT_FK1 FOREIGN KEY(AUDITORIUM_ID) REFERENCES AUDITORIUM(ID),
	CONSTRAINT AUDITORIUM_SEAT_FK2 FOREIGN KEY(SEAT_ID) REFERENCES SEAT(ID)
);



CREATE TABLE RATING (
	ID INT NOT NULL,
	TYPE VARCHAR(256) NOT NULL,
	CONSTRAINT RATING_PK PRIMARY KEY(ID)
);

CREATE TABLE EVENT (
	ID INT NOT NULL,
	NAME VARCHAR(256) NOT NULL,
	BASE_PRICE DOUBLE NOT NULL,
	RATING_ID INT NOT NULL,
	DATE DATE,
	AUDITORIUM_ID INT NOT NULL,
	CONSTRAINT EVENT_PK PRIMARY KEY(ID),
	CONSTRAINT EVENT_FK1 FOREIGN KEY(RATING_ID) REFERENCES RATING(ID),
	CONSTRAINT EVENT_FK2 FOREIGN KEY(AUDITORIUM_ID) REFERENCES AUDITORIUM(ID)
);

CREATE TABLE TICKET (
	ID INT NOT NULL,
	PRICE DOUBLE NOT NULL,
	EVENT_ID INT NOT NULL,
	SEAT_ID INT NOT NULL,
	CONSTRAINT TICKET_PK PRIMARY KEY(ID),
	CONSTRAINT TICKET_FK1 FOREIGN KEY(EVENT_ID) REFERENCES EVENT(ID),
	CONSTRAINT TICKET_FK2 FOREIGN KEY(SEAT_ID) REFERENCES SEAT(ID)
);

CREATE TABLE USER_TICKET (
	USER_ID INT NOT NULL,
	TICKET_ID INT NOT NULL,
	CONSTRAINT USER_TICKET_PK PRIMARY KEY(USER_ID, TICKET_ID),
	CONSTRAINT USER_TICKET_FK1 FOREIGN KEY(USER_ID) REFERENCES USERS(ID),
	CONSTRAINT USER_TICKET_FK2 FOREIGN KEY(TICKET_ID) REFERENCES TICKET(ID)
);







